application: vco-gae
version: 4-1-test
runtime: python
api_version: 1

handlers:
- url: /_static
  static_dir: html/_static

- url: /
  static_files: html/index.html
  upload: html/index.html

- url: /(.*\.(html|js|inv))
  static_files: html/\1
  upload: html/(.*\.(html|js|inv))

- url: /vmware-vmo-webcontrol/.*
  script: vco-server.py

- url: /tasks/.*
  script: vco-tasks.py
  login: admin

builtins:
- datastore_admin: on

- appstats: on

- remote_api: on
