application: vco-gae
version: 1
runtime: python
api_version: 1

handlers:
- url: /_static
  static_dir: html/_static

- url: /
  static_files: html/index.html
  upload: html/index.html

- url: /(.*\.(html|js|inv))
  static_files: html/\1
  upload: html/(.*\.(html|js|inv))

- url: /vmware-vmo-webcontrol/.*
  script: vco-server.py

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /tasks/.*
  script: vco-tasks.py
  login: admin
